// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwbyhoihmkxlqxounyee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Ynlob2lobWt4bHF4b3VueWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzA1NjYsImV4cCI6MjA2NDcwNjU2Nn0.mtLXPDb0_KXHd2FCymmUrxYlO9IKx49w9h-PLFHJHis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);